# Generated by Django 5.1.7 on 2025-03-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_address_userprofile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='contact_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='house',
            name='contact_tel',
        ),
    ]
